# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build From Source

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "17.0"
        directory: ${{runner.temp}}/llvm
    - uses: seanmiddleditch/gha-setup-ninja@v4
    - name: Configure CMake
      run: |
        mkdir -p ${{github.workspace}}/build
        cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G Ninja -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/pebl-install -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target install
    - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            ${{github.workspace}}/pebl-install

